version: '3.2'
services:
  postgres:
    deploy:
      labels:
        com.bsb.dev_contact: malcolm.leehan@bluestembrands.com
        com.bsb.business_contact: malcolm.leehan@bluestembrands.com
        com.bsb.service: spring-book-lib
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M
    environment:
    - PGDATA=/var/lib/postgresql/data/pgdata
    - APP_DB=libDB
    image: harbor.bluestembrands.com/core/postgres:9.6.6-4
    ports:
    - 30019:5432
    networks:
    - swarm-overlay
    volumes:
    - /var/docker-mounts/nfs/data/spring-book-lib/pgdata:/var/lib/postgresql/data/pgdata
networks:
  swarm-overlay:
    external:
      name: swarm-overlay